// Simulation for article on bias of COVID-19 VE related to self-testing
// September 2024
// EpiConcept
// Esther Kissling
// Review
// Part of VEBIS project
// This script is for analysis of the simulated data generated by other do-files (please see associated manuscript)
* We are taking the results from the simulated dataset and estimating mean bias


// Version History
// Created and finalized for distribution with datagen and estimating mean bias scripts
// v3.3 to be consistent with the project

***************************************************************************
* Preliminaries ***********************************************************
***************************************************************************

clear


***************************************************************************************************************	
* Here we summarise the log odds ratios and standard errors from the individual replications and create means
* Using the unadjusted dataset 
***************************************************************************************************************

// Opening the generated simulation data
use simcheck1_postfile1, clear

// Here we analyse the unadjusted results first; we reduce the dataset to improve computational power, with large numbers of repetitions and scenarios
keep if method=="Noadj"	

// Creating the variables to fill:
gen meanlogor=.
gen meanlogse=.
gen or = exp(b)
gen meanve=.
gen meanll=.
gen meanul=.

// Getting the number of distinct categories of scenarios
egen groupvar = group(ve1 st1 s_rr1 possee1 negsee1)
	
qui tab groupvar
local MAX = r(r)

* Creating the new variables for each distinct category
foreach NUM of numlist 1/`MAX' {
		qui mean b if groupvar==`NUM'
		matrix A = r(table)
		replace meanlogor=A[1,1] if groupvar==`NUM' 			// We create a mean of the log odds ratios from the replications for each scenario
		replace meanlogse=A[2,1] if groupvar==`NUM' 				// We capture the standard error of the mean
		replace meanve=(1-exp(A[1,1]))*100 if groupvar==`NUM'	// Here we create the VE from the mean log odds
		* Confidence limits based on standard error
		replace meanll=(1-exp(meanlogor + 1.96 * meanlogse))*100 if groupvar==`NUM'	
		replace meanul=(1-exp(meanlogor - 1.96 * meanlogse))*100 if groupvar==`NUM'
	}
	
	
// Saving only the first obs for each distinct category
bys groupvar: gen count = _n
keep if count==1
drop count
save summarysim_data1, replace
	
// Save to Excel
export excel using "summarysim_data.xls", firstrow(variables) replace

	
***************************************************************************************************************	
* Here we summarise the log odds ratios and standard errors from the individual replications and create means
* Using the adjusted dataset (we expect the estimated VE to be approximately the same as the true VE)
***************************************************************************************************************

// Opening the generated simulation data
use simcheck1_postfile1, clear

// Here we analyse the adjusted results; we reduce the dataset to improve computational power, with large numbers of repetitions and scenarios
keep if method=="Noadj"	

// We save this reduced dataset
* Creating the variables to fill:
gen meanlogor=.
gen meanlogse=.
gen or = exp(b)
gen meanve=.
gen meanll=.
gen meanul=.

* Getting the number of distinct categories of scenarios
egen groupvar = group(ve1 st1 s_rr1 possee1 negsee1)


// Here we analyse the unadjusted results first; we reduce the dataset to improve computational power, with large numbers of repetitions and scenarios
qui tab groupvar
local MAX = r(r)

* Creating the new variables for each distinct category
foreach NUM of numlist 1/`MAX' {
		qui mean b if groupvar==`NUM'
		matrix A = r(table)
		replace meanlogor=A[1,1] if groupvar==`NUM' 			// We create a mean of the log odds ratios from the replications for each scenario
		replace meanlogse=A[2,1] if groupvar==`NUM' 				// We capture the standard error of the mean
		replace meanve=(1-exp(A[1,1]))*100 if groupvar==`NUM'	// Here we create the VE from the mean log odds
		* Confidence limits based on standard error
		replace meanll=(1-exp(meanlogor + 1.96 * meanlogse))*100 if groupvar==`NUM'	
		replace meanul=(1-exp(meanlogor - 1.96 * meanlogse))*100 if groupvar==`NUM'
	}
	
	
// Saving only the first obs for each distinct category
bys groupvar: gen count = _n
keep if count==1
drop count
save summarysim_data1Adj, replace

// Save to Excel
export excel using "summarysim_dataAdj.xls", firstrow(variables) replace

// Clearing the data
clear

